version: 2.1

orbs:
  localstack: localstack/platform@2.0.0

jobs:
  localstack-test:
    executor: localstack/default
    environment:
      CI_PROJECT: ci-demo-1
      DNS_ADDRESS: "0"
    steps:
      - checkout
      - run: docker pull localstack/localstack
      - localstack/startup
      - run:
          name: Deploy app and run test request
          command: |
            docker logs localstack_main
            awslocal s3 mb s3://test123
            awslocal s3 ls
            make install
            make deploy
            make web &
            make send-request
            code=$?
            docker logs localstack_main
            exit $code

workflows:
  localstack-test:
    jobs:
      - localstack-test
